# AnalyzeMyCV
# api/services/latex_templates.py
"""Ten LaTeX resume templates, filled by code from a validated Resume.

Security: no model-written text is ever pasted into LaTeX unescaped. Every string goes
through esc() (and URLs through a whitelist), so a resume that contains `\\input{...}`
or `\\write18` comes out as harmless literal text in the .tex a user compiles.

Every template is a self-contained single file that builds with pdfLaTeX, XeLaTeX or
LuaLaTeX (Overleaf, MiKTeX, TeX Live) using only packages from a standard TeX Live
install. Nothing is compiled on the server.
"""

import re
from dataclasses import dataclass
from typing import Callable, Dict, List

from api.services.resume_data import Entry, Resume, Section

# ---------------------------------------------------------------- escaping

_ESCAPES = {
    "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "<": r"\textless{}", ">": r"\textgreater{}", "|": r"\textbar{}", '"': "''",
    "\u00a0": "~", "\u2013": "--", "\u2014": "---", "\u2018": "`", "\u2019": "'",
    "\u201c": "``", "\u201d": "''", "\u2022": r"\textbullet{}", "\u2026": r"\ldots{}",
    "\u00b7": r"\textperiodcentered{}", "\u2192": r"$\rightarrow$", "\u2212": "-",
}


def esc(value: str) -> str:
    """Escape text for LaTeX. Drops emoji and other characters pdfLaTeX cannot typeset."""
    out = []
    for ch in value or "":
        code = ord(ch)
        if code > 0xFFFF or 0x2600 <= code <= 0x27BF or 0xFE00 <= code <= 0xFE0F:
            continue
        out.append(_ESCAPES.get(ch, ch))
    return "".join(out)


_URL_SAFE = re.compile(r"[^A-Za-z0-9\-._~:/?#\[\]@!&'()*+,;=%]")


def url_arg(url: str) -> str:
    """Whitelist URL characters; only % and # need escaping inside \\href."""
    return _URL_SAFE.sub("", url).replace("%", r"\%").replace("#", r"\#")


def _link(target: str, label: str, underline: bool) -> str:
    text = esc(label)
    if underline:
        text = "\\underline{" + text + "}"
    return "\\href{" + target + "}{" + text + "}"


def href(url: str, label: str, underline: bool = False) -> str:
    return _link(url_arg(url), label, underline)


def mailto(email: str, underline: bool = False) -> str:
    return _link("mailto:" + url_arg(email), email, underline)


def contact_parts(resume: Resume, underline: bool = False) -> List[str]:
    parts = []
    if resume.email:
        parts.append(mailto(resume.email, underline))
    if resume.phone:
        parts.append(esc(resume.phone))
    if resume.location:
        parts.append(esc(resume.location))
    parts += [href(link.url, link.label or re.sub(r"^https?://(www\.)?", "", link.url).rstrip("/"), underline) for link in resume.links]
    return parts


def display_sections(resume: Resume) -> List[Section]:
    """Summary first (as its own section), then the resume's own sections in their original order."""
    sections = list(resume.sections)
    if resume.summary:
        sections.insert(0, Section(title="Summary", text=resume.summary))
    return sections


def split_name(name: str):
    first, _, last = name.strip().rpartition(" ")
    return (first, last) if first else ("", last)


def bullets_env(bullets: List[str], options: str = "", item: str = r"\item ") -> str:
    if not bullets:
        return ""
    body = "\n".join(f"  {item}{esc(b)}" for b in bullets)
    return f"\\begin{{itemize}}{options}\n{body}\n\\end{{itemize}}\n"


def entry_heading(e: Entry):
    """(title, organization): fall back to the organization when there is no title."""
    return (e.title, e.organization) if e.title else (e.organization, "")


# ---------------------------------------------------------------- shared preamble pieces

# pdfLaTeX needs inputenc/fontenc; XeLaTeX/LuaLaTeX need fontspec for Unicode text.
ENGINE = r"""\usepackage{iftex}
\ifPDFTeX
  \usepackage[utf8]{inputenc}
  \usepackage[T1]{fontenc}
  \usepackage{lmodern}
  \input{glyphtounicode}
  \pdfgentounicode=1 % machine-readable / ATS-parsable PDF
\else
  \usepackage{fontspec}
\fi
"""


def _banner(label: str, extra: str = "") -> str:
    return (
        f"% {label}. Generated by AnalyzeMyCV.\n"
        "% Compile with pdfLaTeX, XeLaTeX or LuaLaTeX (for example in Overleaf).\n"
        f"{extra}"
    )


# ---------------------------------------------------------------- 1. Jake's Resume (MIT)

_JAKE_PREAMBLE = r"""\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
__ENGINE__
\pagestyle{fancy}
\fancyhf{} % clear all header and footer fields
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

%-------------------------
% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}
""".replace("__ENGINE__", ENGINE)


def render_jake(r: Resume) -> str:
    out = [
        _banner(
            "Jake's Resume layout",
            "% Based on Jake Gutierrez's resume template (MIT License), itself based on\n"
            "% https://github.com/sb2nov/resume . Copyright (c) 2020 Jake Gutierrez.\n"
            "% Changes: the pdfTeX-only lines are conditional so it also builds with XeLaTeX/LuaLaTeX.\n",
        ),
        _JAKE_PREAMBLE,
        "\\begin{document}\n",
        "\\begin{center}",
        f"    \\textbf{{\\Huge \\scshape {esc(r.name)}}} \\\\ \\vspace{{1pt}}",
    ]
    if r.headline:
        out.append(f"    \\small \\textit{{{esc(r.headline)}}} \\\\")
    out.append("    \\small " + " $|$ ".join(contact_parts(r, underline=True)))
    out.append("\\end{center}\n")
    for s in display_sections(r):
        out.append(f"\\section{{{esc(s.title)}}}")
        if s.text:
            out.append(f"  \\begin{{itemize}}[leftmargin=0.15in, label={{}}]\n    \\item\\small{{{esc(s.text)}}}\n  \\end{{itemize}}")
        if s.skills:
            rows = " \\\\\n      ".join(
                (f"\\textbf{{{esc(k.label)}}}{{: {esc(k.items)}}}" if k.label else esc(k.items)) for k in s.skills
            )
            out.append(f"  \\begin{{itemize}}[leftmargin=0.15in, label={{}}]\n    \\small{{\\item{{\n      {rows}\n    }}}}\n  \\end{{itemize}}")
        if s.entries:
            out.append("  \\resumeSubHeadingListStart")
            for e in s.entries:
                title, org = entry_heading(e)
                out.append(f"    \\resumeSubheading\n      {{{esc(title)}}}{{{esc(e.dates)}}}\n      {{{esc(org)}}}{{{esc(e.location)}}}")
                if e.bullets:
                    out.append("      \\resumeItemListStart")
                    out += [f"        \\resumeItem{{{esc(b)}}}" for b in e.bullets]
                    out.append("      \\resumeItemListEnd")
            out.append("  \\resumeSubHeadingListEnd")
        out.append("")
    out.append("\\end{document}\n")
    return "\n".join(out)


# ---------------------------------------------------------------- 2-5. moderncv (LPPL, ships with TeX Live)

def _render_moderncv(style: str, color: str, label: str):
    def render(r: Resume) -> str:
        first, last = split_name(r.name)
        out = [
            _banner(
                f"moderncv {style} style ({label})",
                "% Uses the moderncv class (LPPL), included in TeX Live and Overleaf.\n",
            ),
            "\\documentclass[11pt,letterpaper,sans]{moderncv}",
            f"\\moderncvstyle{{{style}}}",
            f"\\moderncvcolor{{{color}}}",
            "\\usepackage[scale=0.85]{geometry}",
            f"\\name{{{esc(first)}}}{{{esc(last)}}}",
        ]
        if r.headline:
            out.append(f"\\title{{{esc(r.headline)}}}")
        if r.location:
            out.append(f"\\address{{{esc(r.location)}}}{{}}{{}}")
        if r.phone:
            out.append(f"\\phone[mobile]{{{esc(r.phone)}}}")
        plain_email = bool(r.email) and re.fullmatch(r"[A-Za-z0-9.@-]+", r.email)
        if plain_email:
            out.append(f"\\email{{{r.email}}}")
        def header_link(link) -> str:
            label = link.label or re.sub(r"^https?://(www\.)?", "", link.url).rstrip("/")
            # moderncv processes its header text in a way \href cannot survive when the URL needs % or # escapes.
            return esc(label) if re.search(r"[%#]", link.url) else href(link.url, label)

        links = ([mailto(r.email)] if r.email and not plain_email else []) + [header_link(link) for link in r.links]
        if links:
            out.append("\\extrainfo{" + " \\textbar{} ".join(links) + "}")
        out += ["", "\\begin{document}", "\\makecvtitle", ""]
        for s in display_sections(r):
            out.append(f"\\section{{{esc(s.title)}}}")
            if s.text:
                out.append(f"\\cvitem{{}}{{{esc(s.text)}}}")
            for row in s.skills:
                out.append(f"\\cvitem{{{esc(row.label)}}}{{{esc(row.items)}}}")
            for e in s.entries:
                title, org = entry_heading(e)
                out.append(f"\\cventry{{{esc(e.dates)}}}{{{esc(title)}}}{{{esc(org)}}}{{{esc(e.location)}}}{{}}{{}}")
                out += [f"\\cvlistitem{{{esc(b)}}}" for b in e.bullets]
            out.append("")
        out.append("\\end{document}\n")
        return "\n".join(out)

    return render


# ---------------------------------------------------------------- 6. Classic Serif

def render_classic(r: Resume) -> str:
    out = [
        _banner("Classic Serif"),
        "\\documentclass[11pt,letterpaper]{article}",
        ENGINE,
        "\\usepackage[margin=0.85in]{geometry}",
        "\\usepackage{titlesec}",
        "\\usepackage{enumitem}",
        "\\usepackage[hidelinks]{hyperref}",
        "\\pagestyle{empty}",
        "\\setlength{\\parindent}{0pt}",
        "\\titleformat{\\section}{\\large\\scshape\\raggedright}{}{0em}{}[\\titlerule]",
        "\\titlespacing*{\\section}{0pt}{12pt}{6pt}",
        "",
        "\\begin{document}",
        "\\begin{center}",
        f"  {{\\Huge\\scshape {esc(r.name)}}}\\\\[3pt]",
    ]
    if r.headline:
        out.append(f"  \\textit{{{esc(r.headline)}}}\\\\[2pt]")
    out += ["  " + " \\,$\\cdot$\\, ".join(contact_parts(r)), "\\end{center}", ""]
    for s in display_sections(r):
        out.append(f"\\section{{{esc(s.title)}}}")
        if s.text:
            out.append(f"{esc(s.text)}\\par")
        for k in s.skills:
            out.append((f"\\textbf{{{esc(k.label)}:}} " if k.label else "") + f"{esc(k.items)}\\par")
        for e in s.entries:
            title, org = entry_heading(e)
            out.append(f"\\textbf{{{esc(title)}}}\\hfill {esc(e.dates)}\\par")
            if org or e.location:
                out.append(f"\\textit{{{esc(org)}}}\\hfill\\textit{{{esc(e.location)}}}\\par")
            out.append(bullets_env(e.bullets, "[leftmargin=1.4em,nosep,topsep=3pt]") + "\\vspace{5pt}")
    out.append("\\end{document}\n")
    return "\n".join(out)


# ---------------------------------------------------------------- 7. Modern Sans

def render_modern(r: Resume) -> str:
    out = [
        _banner("Modern Sans"),
        "\\documentclass[11pt,letterpaper]{article}",
        ENGINE,
        "\\usepackage[margin=0.8in]{geometry}",
        "\\usepackage[dvipsnames]{xcolor}",
        "\\usepackage{titlesec}",
        "\\usepackage{enumitem}",
        "\\usepackage[hidelinks]{hyperref}",
        "\\definecolor{accent}{HTML}{1F4E79}",
        "\\renewcommand{\\familydefault}{\\sfdefault}",
        "\\pagestyle{empty}",
        "\\setlength{\\parindent}{0pt}",
        "\\titleformat{\\section}{\\color{accent}\\large\\bfseries}{}{0em}{\\MakeUppercase}[{\\color{accent}\\titlerule[0.8pt]}]",
        "\\titlespacing*{\\section}{0pt}{14pt}{6pt}",
        "",
        "\\begin{document}",
        f"{{\\Huge\\bfseries\\color{{accent}} {esc(r.name)}}}\\\\[4pt]",
    ]
    if r.headline:
        out.append(f"{{\\large {esc(r.headline)}}}\\\\[3pt]")
    out += ["{\\small " + " \\ {\\color{accent}\\textbar}\\ ".join(contact_parts(r)) + "}", ""]
    for s in display_sections(r):
        out.append(f"\\section{{{esc(s.title)}}}")
        if s.text:
            out.append(f"{esc(s.text)}\\par")
        for k in s.skills:
            out.append((f"{{\\bfseries {esc(k.label)}:}} " if k.label else "") + f"{esc(k.items)}\\par\\vspace{{2pt}}")
        for e in s.entries:
            title, org = entry_heading(e)
            out.append(f"{{\\bfseries {esc(title)}}}\\hfill {{\\small {esc(e.dates)}}}\\par")
            if org or e.location:
                out.append(f"{{\\color{{accent}}{esc(org)}}}\\hfill{{\\small {esc(e.location)}}}\\par")
            out.append(bullets_env(e.bullets, "[leftmargin=1.3em,nosep,topsep=3pt]") + "\\vspace{6pt}")
    out.append("\\end{document}\n")
    return "\n".join(out)


# ---------------------------------------------------------------- 8. Compact (one page)

def render_compact(r: Resume) -> str:
    out = [
        _banner("Compact"),
        "\\documentclass[10pt,letterpaper]{article}",
        ENGINE,
        "\\usepackage[margin=0.55in]{geometry}",
        "\\usepackage{titlesec}",
        "\\usepackage{enumitem}",
        "\\usepackage[hidelinks]{hyperref}",
        "\\pagestyle{empty}",
        "\\setlength{\\parindent}{0pt}",
        "\\setlength{\\parskip}{0pt}",
        "\\titleformat{\\section}{\\normalsize\\scshape\\bfseries}{}{0em}{}[\\vspace{-3pt}\\titlerule]",
        "\\titlespacing*{\\section}{0pt}{7pt}{3pt}",
        "",
        "\\begin{document}",
        f"{{\\LARGE\\bfseries {esc(r.name)}}}" + (f"\\quad{{\\large {esc(r.headline)}}}" if r.headline else "") + "\\par\\vspace{2pt}",
        "{\\small " + " \\ $\\cdot$\\ ".join(contact_parts(r)) + "}\\par",
        "",
    ]
    for s in display_sections(r):
        out.append(f"\\section{{{esc(s.title)}}}")
        if s.text:
            out.append(f"{esc(s.text)}\\par")
        for k in s.skills:
            out.append((f"\\textbf{{{esc(k.label)}:}} " if k.label else "") + f"{esc(k.items)}\\par")
        for e in s.entries:
            title, org = entry_heading(e)
            line = f"\\textbf{{{esc(title)}}}" + (f", \\textit{{{esc(org)}}}" if org else "") + (f", {esc(e.location)}" if e.location else "")
            out.append(f"{line}\\hfill {esc(e.dates)}\\par")
            out.append(bullets_env(e.bullets, "[leftmargin=1.1em,nosep,topsep=1pt,itemsep=0pt]", r"\item "))
    out.append("\\end{document}\n")
    return "\n".join(out)


# ---------------------------------------------------------------- 9. Date Column

def render_datecolumn(r: Resume) -> str:
    out = [
        _banner("Date Column"),
        "\\documentclass[11pt,letterpaper]{article}",
        ENGINE,
        "\\usepackage[margin=0.8in]{geometry}",
        "\\usepackage{titlesec}",
        "\\usepackage{enumitem}",
        "\\usepackage[hidelinks]{hyperref}",
        "\\pagestyle{empty}",
        "\\setlength{\\parindent}{0pt}",
        "\\titleformat{\\section}{\\large\\bfseries}{}{0em}{\\MakeUppercase}[\\titlerule]",
        "\\titlespacing*{\\section}{0pt}{12pt}{6pt}",
        "\\newcommand{\\datecol}[2]{\\noindent\\begin{minipage}[t]{0.19\\textwidth}\\raggedright\\small #1\\end{minipage}\\hfill"
        "\\begin{minipage}[t]{0.78\\textwidth}#2\\end{minipage}\\par\\vspace{6pt}}",
        "",
        "\\begin{document}",
        f"{{\\Huge\\bfseries {esc(r.name)}}}\\\\[3pt]",
    ]
    if r.headline:
        out.append(f"{{\\large\\itshape {esc(r.headline)}}}\\\\[3pt]")
    out += ["{\\small " + " \\ $\\cdot$\\ ".join(contact_parts(r)) + "}", ""]
    for s in display_sections(r):
        out.append(f"\\section{{{esc(s.title)}}}")
        if s.text:
            out.append(f"{esc(s.text)}\\par")
        for k in s.skills:
            out.append(f"\\datecol{{\\textbf{{{esc(k.label)}}}}}{{{esc(k.items)}}}")
        for e in s.entries:
            title, org = entry_heading(e)
            head = f"\\textbf{{{esc(title)}}}" + (f", \\textit{{{esc(org)}}}" if org else "") + (f", {esc(e.location)}" if e.location else "")
            body = head + ("\n" + bullets_env(e.bullets, "[leftmargin=1.2em,nosep,topsep=3pt]").strip() if e.bullets else "")
            out.append(f"\\datecol{{{esc(e.dates)}}}{{{body}}}")
    out.append("\\end{document}\n")
    return "\n".join(out)


# ---------------------------------------------------------------- 10. Sidebar (two columns)

def render_sidebar(r: Resume) -> str:
    sections = display_sections(r)
    side = [s for s in sections if s.skills and not s.entries and not s.text]
    main = [s for s in sections if s not in side]

    def body(s: Section) -> List[str]:
        parts = [f"\\section*{{{esc(s.title)}}}"]
        if s.text:
            parts.append(f"{esc(s.text)}\\par")
        for k in s.skills:
            parts.append((f"{{\\bfseries {esc(k.label)}}}\\\\ " if k.label else "") + f"{esc(k.items)}\\par\\vspace{{4pt}}")
        for e in s.entries:
            title, org = entry_heading(e)
            parts.append(f"{{\\bfseries {esc(title)}}}\\hfill {{\\small {esc(e.dates)}}}\\par")
            if org or e.location:
                parts.append(f"{{\\color{{accent}}{esc(org)}}}" + (f", {{\\small {esc(e.location)}}}" if e.location else "") + "\\par")
            parts.append(bullets_env(e.bullets, "[leftmargin=1.2em,nosep,topsep=3pt]") + "\\vspace{5pt}")
        return parts

    out = [
        _banner("Sidebar (two columns)", "% Uses the paracol package.\n"),
        "\\documentclass[10.5pt,letterpaper]{article}",
        ENGINE,
        "\\usepackage[margin=0.7in]{geometry}",
        "\\usepackage[dvipsnames]{xcolor}",
        "\\usepackage{titlesec}",
        "\\usepackage{enumitem}",
        "\\usepackage{paracol}",
        "\\usepackage[hidelinks]{hyperref}",
        "\\definecolor{accent}{HTML}{2E5E4E}",
        "\\renewcommand{\\familydefault}{\\sfdefault}",
        "\\pagestyle{empty}",
        "\\setlength{\\parindent}{0pt}",
        "\\titleformat{\\section}{\\color{accent}\\bfseries}{}{0em}{\\MakeUppercase}[{\\color{accent}\\titlerule[0.6pt]}]",
        "\\titlespacing*{\\section}{0pt}{10pt}{5pt}",
        "\\columnratio{0.30}",
        "\\setlength{\\columnsep}{20pt}",
        "",
        "\\begin{document}",
        f"{{\\Huge\\bfseries\\color{{accent}} {esc(r.name)}}}\\\\[3pt]",
    ]
    if r.headline:
        out.append(f"{{\\large {esc(r.headline)}}}\\par")
    out += ["\\vspace{6pt}", "\\begin{paracol}{2}", "\\section*{Contact}", "\\small"]
    out += [f"{part}\\\\[2pt]" for part in contact_parts(r)]
    out.append("\\normalsize")
    for s in side:
        out += body(s)
    out += ["\\switchcolumn", ""]
    for s in main:
        out += body(s)
    out += ["\\end{paracol}", "\\end{document}\n"]
    return "\n".join(out)


# ---------------------------------------------------------------- registry

@dataclass(frozen=True)
class Template:
    id: str
    label: str
    description: str
    source: str
    render: Callable[[Resume], str]


TEMPLATES: List[Template] = [
    Template("jake", "Jake's Resume", "The most-copied ATS-friendly one-pager on Overleaf: small caps headings, tight bullets.",
             "Jake Gutierrez, MIT License", render_jake),
    Template("moderncv-classic", "ModernCV Classic", "Timeline-style entries with a blue accent.",
             "moderncv class (LPPL)", _render_moderncv("classic", "blue", "blue")),
    Template("moderncv-banking", "ModernCV Banking", "Shaded section bars; conservative, finance-friendly.",
             "moderncv class (LPPL)", _render_moderncv("banking", "blue", "blue")),
    Template("moderncv-casual", "ModernCV Casual", "Left date column with a bold coloured header.",
             "moderncv class (LPPL)", _render_moderncv("casual", "green", "green")),
    Template("moderncv-fancy", "ModernCV Fancy", "Header with icons and coloured section titles.",
             "moderncv class (LPPL)", _render_moderncv("fancy", "burgundy", "burgundy")),
    Template("classic-serif", "Classic Serif", "Centered name, small-caps rules; the traditional look.", "Built-in", render_classic),
    Template("modern-sans", "Modern Sans", "Sans-serif with a navy accent and left-aligned header.", "Built-in", render_modern),
    Template("compact", "Compact", "Dense single-line entries to fit a lot on one page.", "Built-in", render_compact),
    Template("date-column", "Date Column", "Dates in a left column, details on the right; common in CVs.", "Built-in", render_datecolumn),
    Template("sidebar", "Sidebar", "Two columns: contact and skills on the left, experience on the right.", "Built-in", render_sidebar),
]
TEMPLATES_BY_ID: Dict[str, Template] = {t.id: t for t in TEMPLATES}


def render_all(resume: Resume) -> List[dict]:
    return [
        {"id": t.id, "label": t.label, "description": t.description, "source": t.source, "tex": t.render(resume)}
        for t in TEMPLATES
    ]
