# AnalyzeMyCV
# api/models.py

from typing import Optional

from pydantic import BaseModel, Field


# Defining Response Schema
class AnalysisResponse(BaseModel):
    # Schema For The Response Containing The Structured Analysis Report

    success: bool = True
    report: Optional[str] = Field(
        None, description="The detailed text report generated by the LLM."
    )
    metadata: dict = Field(
        default_factory=dict, description="Any metadata about the analysis process."
    )
