# AnalyzeMyCV
# api/models.py

from typing import List, Optional

from pydantic import BaseModel, Field


class LatexTemplate(BaseModel):
    # One rendering of a generated resume as a self-contained .tex file
    id: str
    label: str
    description: str
    source: str
    tex: str


# Defining Response Schema
class AnalysisResponse(BaseModel):
    # Schema For The Response Containing The Structured Analysis Report

    success: bool = True
    report: Optional[str] = Field(
        None, description="The detailed text report generated by the LLM."
    )
    latex: Optional[List[LatexTemplate]] = Field(
        None, description="The generated resume rendered in each LaTeX template (resume generation only)."
    )
    metadata: dict = Field(
        default_factory=dict, description="Any metadata about the analysis process."
    )
