name: Build and deploy Python app to Azure Web App - analyzemycv

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB5D6BFC239848FF8D4B80BDD69BEC84 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95898585A26C4FBE8299EEBFAA256519 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE5649E63E324F0F8EF90C09B80B4A0E }}

      - name: Deploy raw source to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'analyzemycv'
          slot-name: 'Production'
          package: '.'
          startup-command: 'chmod +x ./entrypoint.sh && ./entrypoint.sh'
